export const UPDATE_HEADLINE = 'UPDATE_HEADLINE'
export const GET_HEADLINE = 'GET_HEADLINE'

export const UPDATE_ACTIVE_TAB = 'UPDATE_ACTIVE_TAB'

export const GET_TOOTH_LIST = 'GET_TOOTH_LIST'
export const GET_TOOTH_LIST_FAILURE = 'GET_TOOTH_LIST_FAILURE'
export const SUBMIT_TOOTH = 'SUBMIT_TOOTH'
export const SUBMIT_TOOTH_FAILURE = 'SUBMIT_TOOTH_FAILURE'
export const SET_CURRENTTEETH = 'SET_CURRENTTEETH'
export const SET_CURRENTBLOCK = 'SET_CURRENTBLOCK'
export const ADD_CARIES_LIST = 'ADD_CARIES_LIST'
export const REMOVE_CARIES_LIST = 'REMOVE_CARIES_LIST'
export const ADD_BROKEN_LIST = 'ADD_BROKEN_LIST'
export const REMOVE_BROKEN_LIST = 'REMOVE_BROKEN_LIST'

export const SUBMIT_QUESTIONNAIRE = 'SUBMIT_QUESTIONNAIRE'

export const SUBMIT_CONDITION = 'SUBMIT_CONDITION'
export const CLEAN_CONDITION = 'CLEAN_CONDITION'

export const GET_TOOTH_PIC = 'GET_TOOTH_PIC'
export const SUBMIT_TOOTH_PIC = 'SUBMIT_TOOTH_PIC'
export const DELETE_TOOTH_PIC = 'DELETE_TOOTH_PIC'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const CLEAN_QUESTIONNAIRE = 'CLEAN_QUESTIONNAIRE'
export const CLEAN_TOOTH = 'CLEAN_TOOTH'
export const CLEAN_TOOTH_PIC = 'CLEAN_TOOTH_PIC'
export const CLEAN_USER = 'CLEAN_USER'
